### ISSUE TITLE
Plantage Homebridge

### ISSUE THREAD

**Issue by 2manyk** [alxscms/homebridge-somfy-protect#13]
Bonjour, dès que j'installe le plugin sur la derniere version de homebridge, celui plante en boucle, je suis obligé de désactiver le plugin pour que tout revienne à la normale.

Ci-dessous le code erreur : 

rror: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/homebridge-somfy-protect/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-somfy-protect/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-somfy-protect/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Leyomgui** [comment]
Hello,

un cas similaire est reporté ici en commentaire :[https://www.mamili-homekit.fr/homebridge-somfy-protect/]

**Comment by 2manyk** [comment]
Effectivement, le commentaire sur le site mamili-homekit viens de moi :)

**Comment by alxscms** [comment]
Est-ce que tu as toujours le problème ?
